#!/bin/sh

dirname="$(dirname "$0")"

distro_config_file="$dirname/../distro-config.sh"
if [ ! -e "$distro_config_file" ]; then
        printf '%s: %s does not exist. Aborting...\n' "$0" "$distro_config_file" >&2
        exit 1
fi

# shellcheck source=../distro-config.sh
. "$distro_config_file"

mkdir -p "$DISTRO_BASE_DIRECTORY"
mkdir -p "$DISTRO_SCRIPT_DIRECTORY"
mkdir -p "$DISTRO_EXPORT_DIRECTORY"
mkdir -p "$DISTRO_ALIAS_DIRECTORY"

# Copy config.sh to distro base directory for runtime use
cp "$distro_config_file" "$DISTRO_BASE_DIRECTORY/distro-config.sh"

# Generate bootstrap file with base directory location
distro_bootstrap_file="$HOME/.distro-bootstrap"
cat > "$distro_bootstrap_file" <<EOF
#!/bin/sh
# Bootstrap file - contains only the distro base directory location
# Generated by distro-setup/shell/setup.sh
DISTRO_BASE_DIRECTORY="$DISTRO_BASE_DIRECTORY"
export DISTRO_BASE_DIRECTORY
EOF

# Copy over inputrc so I stop hearing that damn bell
inputrc="$dirname"'/common/.inputrc'
if [ ! -e "$inputrc" ]; then
        printf '%s: %s does not exist. Aborting...\n' "$0" "$inputrc" >&2
        exit 1
fi
cp "$inputrc" "$HOME"


common_script_directory="$dirname"'/common/script'
if [ ! -d "$common_script_directory" ]; then
        printf '%s: %s does not exist. Aborting...\n' "$0" "$common_script_directory" >&2
        exit 1
fi
cp "$common_script_directory"/* "$DISTRO_SCRIPT_DIRECTORY"


common_export_file="$dirname"'/common/common-export.sh'
if [ ! -e "$common_export_file" ]; then
        printf '%s: %s does not exist. Aborting...\n' "$0" "$common_export_file" >&2
        exit 1
fi
# Copy over exports that are common across all shells
cp "$common_export_file" "$DISTRO_EXPORT_DIRECTORY"


common_alias_file="$dirname"'/common/common-alias.sh'
if [ ! -e "$common_alias_file" ]; then
        printf '%s: %s does not exist. Aborting...\n' "$0" "$common_alias_file" >&2
        exit 1
fi
cp "$common_alias_file" "$DISTRO_ALIAS_DIRECTORY"

# We only want to truly install bourne shell
# configs if it isn't a symlink to another implementation
# Example: Debian links /bin/sh to dash while FreeBSD has a true
# bourne shell implementation

if [ "$SHELL" = '/bin/sh' ] && [ ! -L "$SHELL" ]; then
        echo 'Detected Bourne shell. Installing configs...'
        "$dirname"'/sh/setup.sh'
elif [ "$SHELL" = '/bin/bash' ]; then
        echo 'Detected bash shell. Installing configs...'
        "$dirname"'/bash/setup.sh'
else
        printf '%s: Could not detect shell installed. Aborting...\n' "$0" >&2
        exit 1
fi
