colorscheme molokai
syntax on
set number

" Expand tabs to spaces when using tab key
set expandtab 
set tabstop=8

" Sets the level of identation(spaces) for auto indent
" Includes | 'cindent(Automatic C indentation) | >>(Indent line rightward) and
" << (Indent line leftward)
set shiftwidth=8

filetype plugin indent on

" Shows incomplete commands being typed in the lower right hand corner
set showcmd

" Shows the current position of the cursor in the file at the lower right hand
" corner (rows, columns) 
set ruler

" Sets .netrwhist file to zero so it doesn't track 
" modified directory history
let g:netrw_dirhistmax = 0

let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": get(split($TMUX, ","), 0), "target_pane": ":.1"}
